# Generated by Django 5.1.1 on 2024-10-08 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10)),
                ('recognition_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.camera')),
            ],
        ),
    ]
